# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/student/Desktop/1/assgn1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/student/Desktop/1/assgn1/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/student/Desktop/1/assgn1/count01.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top count01 -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef count01.dcp

catch { report_utilization -file count01_utilization_synth.rpt -pb count01_utilization_synth.pb }
